package datamanagement.uis;

import datamanagement.entities.IRecord;
import datamanagement.entities.IStudent;
import datamanagement.entities.ISubject;
import datamanagement.controllers.CheckGradeController;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class CheckGradeUserInterface extends javax.swing.JFrame implements IUnitLister, IStudentLister {
	
	private CheckGradeController controller_;
	private javax.swing.DefaultComboBoxModel<String> unitModel_;
	private javax.swing.DefaultComboBoxModel<String> studentModel_;
	float asg1Mark_;
	float asg2Mark_;
	float examMark_;
	Integer studentId_;

	public CheckGradeUserInterface(CheckGradeController controller) {
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				controller_.close();
			}
		});
		this.controller_ = controller;
		unitModel_ = new javax.swing.DefaultComboBoxModel<>(new String[0]);
		studentModel_ = new javax.swing.DefaultComboBoxModel<>(new String[0]);
		initComponents();
		unitComboBox_.setModel(unitModel_);
		studentComboBox_.setModel(studentModel_);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
		unitPanel = new javax.swing.JPanel();
		unitComboBox_ = new javax.swing.JComboBox<>();
		studentPanel = new javax.swing.JPanel();
		studentComboBox_ = new javax.swing.JComboBox<>();
		markPanel = new javax.swing.JPanel();
		javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
		javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
		javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
		asg1MarkTextField = new javax.swing.JTextField();
		asg2MarkTextField = new javax.swing.JTextField();
		examMarkTextField = new javax.swing.JTextField();
		changeButton = new javax.swing.JButton();
		saveButton = new javax.swing.JButton();
		gradePanel = new javax.swing.JPanel();
		gradeLabel = new javax.swing.JLabel();
		checkGradeButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
		jLabel1.setText("Check Grade UI");

		unitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Unit"));

		unitComboBox_.setModel(unitModel_);
		unitComboBox_.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				unitComboBoxItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout gl_unitPanel = new javax.swing.GroupLayout(unitPanel);
		unitPanel.setLayout(gl_unitPanel);
		gl_unitPanel.setHorizontalGroup(gl_unitPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_unitPanel.createSequentialGroup().addContainerGap()
						.addComponent(unitComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		gl_unitPanel.setVerticalGroup(gl_unitPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_unitPanel.createSequentialGroup()
						.addComponent(unitComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		studentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));

		studentComboBox_.setModel(studentModel_);
		studentComboBox_.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				studentComboBoxItemStateChanged(evt);
			}
		});

		javax.swing.GroupLayout gl_studentPanel = new javax.swing.GroupLayout(studentPanel);
		studentPanel.setLayout(gl_studentPanel);
		gl_studentPanel.setHorizontalGroup(gl_studentPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_studentPanel.createSequentialGroup().addContainerGap()
						.addComponent(studentComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE, 185,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		gl_studentPanel.setVerticalGroup(gl_studentPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_studentPanel.createSequentialGroup()
						.addComponent(studentComboBox_, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		markPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Marks"));

		jLabel2.setText("Asg1:");

		jLabel3.setText("Asg2:");

		jLabel4.setText("Exam:");

		asg1MarkTextField.setEditable(false);
		asg1MarkTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				markTextFieldKeyTyped(evt);
			}
		});

		asg2MarkTextField.setEditable(false);

		examMarkTextField.setEditable(false);

		changeButton.setText("Change");
		changeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				changeActionPerformed(evt);
			}
		});

		saveButton.setText("Save");
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout gl_markPanel = new javax.swing.GroupLayout(markPanel);
		markPanel.setLayout(gl_markPanel);
		gl_markPanel.setHorizontalGroup(gl_markPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_markPanel.createSequentialGroup()
						.addGroup(gl_markPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(gl_markPanel.createSequentialGroup().addContainerGap().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(asg1MarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel3))
								.addGroup(gl_markPanel.createSequentialGroup().addGap(85, 85, 85).addComponent(
										changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(gl_markPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(gl_markPanel.createSequentialGroup().addGap(18, 18, 18)
										.addComponent(asg2MarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel4).addGap(18, 18, 18)
										.addComponent(examMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(gl_markPanel.createSequentialGroup().addGap(53, 53, 53).addComponent(
										saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(15, 15, 15)));
		gl_markPanel.setVerticalGroup(gl_markPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_markPanel.createSequentialGroup()
						.addGroup(gl_markPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(asg1MarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3)
						.addComponent(asg2MarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4).addComponent(examMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(gl_markPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(changeButton).addComponent(saveButton))
						.addContainerGap()));

		gradePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Grade"));

		gradeLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		gradeLabel.setForeground(new java.awt.Color(255, 0, 0));
		gradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		gradeLabel.setText("grade");

		javax.swing.GroupLayout gl_gradePanel = new javax.swing.GroupLayout(gradePanel);
		gradePanel.setLayout(gl_gradePanel);
		gl_gradePanel.setHorizontalGroup(gl_gradePanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(gradeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						153, Short.MAX_VALUE));
		gl_gradePanel.setVerticalGroup(gl_gradePanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(gl_gradePanel.createSequentialGroup().addGap(34, 34, 34).addComponent(gradeLabel)
						.addContainerGap(43, Short.MAX_VALUE)));

		checkGradeButton.setText("Check Grade");
		checkGradeButton.setActionCommand("checkGrade");
		checkGradeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				checkGradeActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(markPanel, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(unitPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18).addComponent(gradePanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGroup(layout.createSequentialGroup().addGap(161, 161, 161).addComponent(checkGradeButton))
						.addGroup(layout.createSequentialGroup().addGap(157, 157, 157).addComponent(jLabel1)))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(13, 13, 13)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(unitPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(studentPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(gradePanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(markPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(checkGradeButton)
				.addGap(58, 58, 58)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	
	
	private void unitComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {
		String currentUnit = (String) unitComboBox_.getSelectedItem();
		resetAllFields();
		clearStudents();
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (currentUnit.equals((String) unitComboBox_.getItemAt(0))) {
				currentUnit = "NONE";
			}
			controller_.unitSelected(currentUnit);
		}
	}

	
	
	private void studentComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {
		resetAllFields();
		String currentStudent = (String) studentComboBox_.getSelectedItem();
		
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			if (currentStudent.equals((String) studentComboBox_.getItemAt(0))) {
				studentId_ = new Integer(0);
			} 
			else {
				studentId_ = new Integer(currentStudent.split("\\s")[0]);
			}
			controller_.studentSelected(studentId_);
		}
	}

	
	
	private void checkGradeActionPerformed(java.awt.event.ActionEvent evt) {
		asg1Mark_ = new Float(asg1MarkTextField.getText()).floatValue();
		asg2Mark_ = new Float(asg2MarkTextField.getText()).floatValue();
		examMark_ = new Float(examMarkTextField.getText()).floatValue();
		String grade = controller_.checkGrade(asg1Mark_, asg2Mark_, examMark_);
		gradeLabel.setText(grade);
	}

	
	
	private void changeActionPerformed(java.awt.event.ActionEvent evt) {
		controller_.enableChangeMarks();
		gradeLabel.setText("");
	}


	
	private void markTextFieldKeyTyped(java.awt.event.KeyEvent evt) {
		gradeLabel.setText("");
	}

	
	
	private void saveActionPerformed(java.awt.event.ActionEvent evt) {
		float asg1Mark = new Float(asg1MarkTextField.getText()).floatValue();
		float asg2Mark = new Float(asg2MarkTextField.getText()).floatValue();
		float examMark = new Float(examMarkTextField.getText()).floatValue();
		controller_.saveGrade(asg1Mark, asg2Mark, examMark);
		checkGradeActionPerformed(null);
	}

	
	
	public void clearUnits() {
		unitModel_.removeAllElements();
		unitModel_.addElement("<none selected>");
		clearStudents();
	}

	
	
	public void addUnit(ISubject u) {
		unitModel_.addElement(u.getSubjectCode());
	}

	
	
	public void setUnitComboBoxEnabled(boolean b) {
		unitComboBox_.setEnabled(b);
	}

	
	
	public void clearStudents() {
		studentModel_.removeAllElements();
		studentModel_.addElement("<none selected>");
	}

	
	
	public void addStudent(IStudent student) {
		studentModel_.addElement(student.getID().toString() + " : " + 
	                             student.getFirstName() + " " + 
				                 student.getLastName());
	}

	
	
	public void setStudentComboBoxEnabled(boolean b) {
		studentComboBox_.setEnabled(b);
	}

	
	
	public void setRecord(IRecord record) {
		asg1MarkTextField.setText(new Float(record.getAsg1Mark()).toString());
		asg2MarkTextField.setText(new Float(record.getAsg2Mark()).toString());
		examMarkTextField.setText(new Float(record.getExamMark()).toString());
		gradeLabel.setText("");
		// setEnableChangeMarks(true);
	}

	
	
	public void resetAllFields() {
		asg1MarkTextField.setText("");
		asg2MarkTextField.setText("");
		examMarkTextField.setText("");
		gradeLabel.setText("");
		asg1MarkTextField.setEditable(false);
		asg2MarkTextField.setEditable(false);
		examMarkTextField.setEditable(false);
	}

	
	
	public void setCheckButtonEnabled(boolean b) {
		checkGradeButton.setEnabled(b);
	}

	
	
	public void setChangeButtonEnabled(boolean b) {
		changeButton.setEnabled(b);
		// gradeLB.setText("");
	}

	
	
	public void setMarkFieldsEditableSaveButtonEnabled(boolean b) {
		asg1MarkTextField.setEditable(b);
		asg2MarkTextField.setEditable(b);
		examMarkTextField.setEditable(b);
		saveButton.setEnabled(b);
	}

	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton changeButton;
	private javax.swing.JButton saveButton;
	private javax.swing.JButton checkGradeButton;
	private javax.swing.JComboBox<String> unitComboBox_;
	private javax.swing.JComboBox<String> studentComboBox_;
	private javax.swing.JLabel gradeLabel;
	private javax.swing.JPanel unitPanel;
	private javax.swing.JPanel studentPanel;
	private javax.swing.JPanel markPanel;
	private javax.swing.JPanel gradePanel;
	private javax.swing.JTextField asg1MarkTextField;
	private javax.swing.JTextField asg2MarkTextField;
	private javax.swing.JTextField examMarkTextField;
	// End of variables declaration//GEN-END:variables
}
